# Analyse de la maille cristalline du CaCN2
## Chargement des modules et du fichier

In [53]:
import numpy as np
import pandas as pd
from mp_api.client import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [54]:
mp_key = "wjMeCvxez5rqgsz8tYQIQIC7njLkvYiq"
mp_id = "mp-4124"

In [55]:
print("Téléchargement du fichier")
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
print("Téléchargement effectué avec succès")

Téléchargement du fichier


Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Téléchargement effectué avec succès


## Analyse des paramères de la maille cristalline

In [56]:
spaceAnalyzer = SpacegroupAnalyzer(prim_struc)



In [57]:
#Obtenir la structure
data = spaceAnalyzer.get_primitive_standard_structure()

#Paramètres de maille primitive
a = data.lattice.a
alpha = data.lattice.alpha

In [58]:
#Type de maille 
latticeType = spaceAnalyzer.get_lattice_type()
print("lattice type =",str(latticeType))
#Système cristallin 
crystal_system = spaceAnalyzer.get_crystal_system()
print("cristal system =",str(crystal_system))
#Groupe ponctuel
group = spaceAnalyzer.get_point_group_symbol()
print("poncual group =",str(group))

lattice type = rhombohedral
cristal system = trigonal
poncual group = -3m


In [59]:
#Réseau direct primitif
#Convertir dans le système rhomboédrique 
direct_Network = spaceAnalyzer.find_primitive().lattice.rhombohedral(a, alpha)
print("Vecteurs du réseau direct : ")
print(direct_Network.matrix)


Vecteurs du réseau direct : 
[[3.46866658 0.         4.11169889]
 [1.50268632 3.12627281 4.11169889]
 [0.         0.         5.37937874]]


In [63]:
#Réseau réciproque primitif
reciprocal_Network = spaceAnalyzer.find_primitive().lattice.rhombohedral(a,alpha).reciprocal_lattice
print("Vecteurs du réseau réciproque : ")
print(reciprocal_Network.matrix)


Vecteurs du réseau réciproque : 
[[ 1.8114123  -0.87068041  0.        ]
 [ 0.          2.00980071  0.        ]
 [-1.38454314 -0.87068041  1.16801319]]


## Affichage des résultats

In [ ]:
données =  [
    ("----Réseau direct maille primitive----", ""),
    ("Vecteur a", direct_Network.matrix[0]),
    ("Vecteur b", direct_Network.matrix[1]),
    ("Vecteur c", direct_Network.matrix[2]),
    ("Longueurs (a, b, c)", direct_Network.abc),
    ("Angles (α, β, γ)", direct_Network.angles),
    ("", ""),
    ("----Réseau réciproque maille primitive----", ""),
    ("Vecteur a*", reciprocal_Network.matrix[0]),
    ("Vecteur b*", reciprocal_Network.matrix[1]),
    ("Vecteur c*", reciprocal_Network.matrix[2]),
    ("Longueurs (a*, b*, c*)", reciprocal_Network.abc),
    ("Angles (α*, β*, γ*)", reciprocal_Network.angles),
    ("", ""),
    ("----Informations cristallographiques----", ""),
    ("Type de maille", latticeType),
    ("Système cristallin", crystal_system),
    ("Groupe ponctuel", group),
]

# Création du DataFrame
df = pd.DataFrame(données, columns=["Propriété", "Valeur"])

for index, row in df.iterrows():
    if row["Propriété"] == "": 
        print()
    else:
        print(f"{row['Propriété']: <30} {row['Valeur']}")