# Analyse de la maille cristalline du CaCN2
## Chargement des modules et du fichier

In [1]:
import numpy as np
import pandas as pd
from mp_api.client import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
mp_key = "wjMeCvxez5rqgsz8tYQIQIC7njLkvYiq"
mp_id = "mp-4124"

In [3]:
print("Téléchargement du fichier")
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
print("Téléchargement effectué avec succès")

Téléchargement du fichier


Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Téléchargement effectué avec succès


## Analyse des paramères de la maille cristalline

In [4]:
spaceAnalyzer = SpacegroupAnalyzer(prim_struc)
#Obtenir la structure
data = spaceAnalyzer.get_primitive_standard_structure()
data2 = spaceAnalyzer.get_conventional_standard_structure()

In [5]:
#Type de maille 
latticeType = spaceAnalyzer.get_lattice_type()
print("lattice type =",str(latticeType))
#Système cristallin 
crystal_system = spaceAnalyzer.get_crystal_system()
print("cristal system =",str(crystal_system))
#Groupe ponctuel
group = spaceAnalyzer.get_point_group_symbol()
print("poncual group =",str(group))

lattice type = rhombohedral
cristal system = trigonal
poncual group = -3m


In [6]:
#Réseau direct primitif
#Convertir dans le système rhomboédrique 
direct_Network = data.lattice
print("Vecteurs du réseau direct maille primitive :")
print(direct_Network.matrix)
#Réseau direct conventionnel
direct_Network2 = data2.lattice
print("Vecteurs du réseau direct maille conventionnelle :")
print(direct_Network2.matrix)

Vecteurs du réseau direct maille primitive :
[[ 5.05252913 -1.84652782  0.        ]
 [ 5.05252913  1.84652782  0.        ]
 [ 4.37768591  0.          3.12627281]]
Vecteurs du réseau direct maille conventionnelle :
[[ 1.84652782 -3.19828001  0.        ]
 [ 1.84652782  3.19828001  0.        ]
 [ 0.          0.         14.81632411]]


In [7]:
#Réseau réciproque primitif
reciprocal_Network = data.lattice.reciprocal_lattice
print("Vecteurs du réseau réciproque maille primitive: ")
print(reciprocal_Network.matrix)
#Réseau réciproque conventionnel
reciprocal_Network2 = data2.lattice.reciprocal_lattice
print("Vecteurs du réseau réciproque maille conventionnelle: ")
print(reciprocal_Network2.matrix)


Vecteurs du réseau réciproque maille primitive: 
[[ 0.62178615 -1.70135137 -0.87068041]
 [ 0.62178615  1.70135137 -0.87068041]
 [ 0.          0.          2.00980071]]
Vecteurs du réseau réciproque maille conventionnelle: 
[[ 1.70135137 -0.98227567  0.        ]
 [ 1.70135137  0.98227567  0.        ]
 [ 0.          0.          0.4240718 ]]


## Affichage des résultats

In [8]:
données =  [
    ("----Informations cristallographiques----", ""),
    ("Type de maille", latticeType),
    ("Système cristallin", crystal_system),
    ("Groupe ponctuel", group),
    ("", ""),
    ("-------Maille primitive-------", ""),
    ("----Réseau direct----", ""),
    ("Vecteur a", direct_Network.matrix[0]),
    ("Vecteur b", direct_Network.matrix[1]),
    ("Vecteur c", direct_Network.matrix[2]),
    ("Longueurs (a, b, c)", direct_Network.abc),
    ("Angles (α, β, γ)", direct_Network.angles),
    ("", ""),
    ("----Réseau réciproque----", ""),
    ("Vecteur a*", reciprocal_Network.matrix[0]),
    ("Vecteur b*", reciprocal_Network.matrix[1]),
    ("Vecteur c*", reciprocal_Network.matrix[2]),
    ("Longueurs (a*, b*, c*)", reciprocal_Network.abc),
    ("Angles (α*, β*, γ*)", reciprocal_Network.angles),
    ("", ""),
    ("-------Maille conventionnelle-------",""),
    ("----Réseau direct----", ""),
    ("Vecteur a", direct_Network2.matrix[0]),
    ("Vecteur b", direct_Network2.matrix[1]),
    ("Vecteur c", direct_Network2.matrix[2]),
    ("Longueurs (a, b, c)", direct_Network2.abc),
    ("Angles (α, β, γ)", direct_Network2.angles),
    ("", ""),
    ("----Réseau réciproque----", ""),
    ("Vecteur a*", reciprocal_Network2.matrix[0]),
    ("Vecteur b*", reciprocal_Network2.matrix[1]),
    ("Vecteur c*", reciprocal_Network2.matrix[2]),
    ("Longueurs (a*, b*, c*)", reciprocal_Network2.abc),
    ("Angles (α*, β*, γ*)", reciprocal_Network2.angles),
    
]

# Création du DataFrame
df = pd.DataFrame(données, columns=["Propriété", "Valeur"])

for index, row in df.iterrows():
    if row["Propriété"] == "": 
        print()
    else:
        print(f"{row['Propriété']: <30} {row['Valeur']}")

----Informations cristallographiques---- 
Type de maille                 rhombohedral
Système cristallin             trigonal
Groupe ponctuel                -3m

-------Maille primitive------- 
----Réseau direct----          
Vecteur a                      [ 5.05252913 -1.84652782  0.        ]
Vecteur b                      [5.05252913 1.84652782 0.        ]
Vecteur c                      [4.37768591 0.         3.12627281]
Longueurs (a, b, c)            (5.379378735817053, 5.379378735817053, 5.379378735817053)
Angles (α, β, γ)               (40.15128337588714, 40.15128337588714, 40.15128337588714)

----Réseau réciproque----      
Vecteur a*                     [ 0.62178615 -1.70135137 -0.87068041]
Vecteur b*                     [ 0.62178615  1.70135137 -0.87068041]
Vecteur c*                     [0.         0.         2.00980071]
Longueurs (a*, b*, c*)         (2.009800710811831, 2.0098007108118314, 2.0098007108118314)
Angles (α*, β*, γ*)            (115.67191115040721, 115.67191115040